/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type RYieldFundingSummaryStruct = {
  longConfirmed: BigNumberish;
  longPending: BigNumberish;
  shortConfirmed: BigNumberish;
  shortPending: BigNumberish;
  longAccrued: BigNumberish;
  shortAccrued: BigNumberish;
  settlePending: boolean;
  vaultClaimableLong: BigNumberish;
  vaultClaimableShort: BigNumberish;
  vaultAccruedLong: BigNumberish;
  vaultAccruedShort: BigNumberish;
};

export type RYieldFundingSummaryStructOutput = [
  longConfirmed: bigint,
  longPending: bigint,
  shortConfirmed: bigint,
  shortPending: bigint,
  longAccrued: bigint,
  shortAccrued: bigint,
  settlePending: boolean,
  vaultClaimableLong: bigint,
  vaultClaimableShort: bigint,
  vaultAccruedLong: bigint,
  vaultAccruedShort: bigint
] & {
  longConfirmed: bigint;
  longPending: bigint;
  shortConfirmed: bigint;
  shortPending: bigint;
  longAccrued: bigint;
  shortAccrued: bigint;
  settlePending: boolean;
  vaultClaimableLong: bigint;
  vaultClaimableShort: bigint;
  vaultAccruedLong: bigint;
  vaultAccruedShort: bigint;
};

export type RYieldUserSummaryStruct = {
  shares: BigNumberish;
  fundingShares: BigNumberish;
  assetsUsdc: BigNumberish;
  hedgedUsdc: BigNumberish;
  idleShareUsdc: BigNumberish;
  maxWithdrawableUsdc: BigNumberish;
  redeemShares: BigNumberish;
  claimableUsdc: BigNumberish;
};

export type RYieldUserSummaryStructOutput = [
  shares: bigint,
  fundingShares: bigint,
  assetsUsdc: bigint,
  hedgedUsdc: bigint,
  idleShareUsdc: bigint,
  maxWithdrawableUsdc: bigint,
  redeemShares: bigint,
  claimableUsdc: bigint
] & {
  shares: bigint;
  fundingShares: bigint;
  assetsUsdc: bigint;
  hedgedUsdc: bigint;
  idleShareUsdc: bigint;
  maxWithdrawableUsdc: bigint;
  redeemShares: bigint;
  claimableUsdc: bigint;
};

export type RYieldVaultSummaryStruct = {
  marketId: BytesLike;
  vault: AddressLike;
  distributor: AddressLike;
  rToken: AddressLike;
  oracle: AddressLike;
  assetName: string;
  state: BigNumberish;
  totalShares: BigNumberish;
  totalAssetsUsdc: BigNumberish;
  pricePerShareWad: BigNumberish;
  idleUsdc: BigNumberish;
  hedgedAssetsUsdc: BigNumberish;
  longValueUsdc: BigNumberish;
  shortEquityUsdc: BigNumberish;
  currentGapBps: BigNumberish;
  entryGapBps: BigNumberish;
  hedgedNotionalUsdc: BigNumberish;
  depositCap: BigNumberish;
  minDeposit: BigNumberish;
  perfFeeBps: BigNumberish;
  targetLeverage: BigNumberish;
  hwmAssetsPerShareWad: BigNumberish;
  execFee: BigNumberish;
  execFeeBalance: BigNumberish;
  pendingOrderKey: BytesLike;
  pendingCreatedAt: BigNumberish;
  fundingSettlePending: boolean;
  oraclePrice8: BigNumberish;
  ammPrice8: BigNumberish;
  pool: AddressLike;
  reservedClaimableUsdc: BigNumberish;
  totalRedeemShares: BigNumberish;
  settlingEpoch: BigNumberish;
  settlingRemainingShares: BigNumberish;
  gapCheckEnabled: boolean;
  maxPriceImpactBps: BigNumberish;
  maxEntryPremiumBps: BigNumberish;
  maxExitDiscountBps: BigNumberish;
};

export type RYieldVaultSummaryStructOutput = [
  marketId: string,
  vault: string,
  distributor: string,
  rToken: string,
  oracle: string,
  assetName: string,
  state: bigint,
  totalShares: bigint,
  totalAssetsUsdc: bigint,
  pricePerShareWad: bigint,
  idleUsdc: bigint,
  hedgedAssetsUsdc: bigint,
  longValueUsdc: bigint,
  shortEquityUsdc: bigint,
  currentGapBps: bigint,
  entryGapBps: bigint,
  hedgedNotionalUsdc: bigint,
  depositCap: bigint,
  minDeposit: bigint,
  perfFeeBps: bigint,
  targetLeverage: bigint,
  hwmAssetsPerShareWad: bigint,
  execFee: bigint,
  execFeeBalance: bigint,
  pendingOrderKey: string,
  pendingCreatedAt: bigint,
  fundingSettlePending: boolean,
  oraclePrice8: bigint,
  ammPrice8: bigint,
  pool: string,
  reservedClaimableUsdc: bigint,
  totalRedeemShares: bigint,
  settlingEpoch: bigint,
  settlingRemainingShares: bigint,
  gapCheckEnabled: boolean,
  maxPriceImpactBps: bigint,
  maxEntryPremiumBps: bigint,
  maxExitDiscountBps: bigint
] & {
  marketId: string;
  vault: string;
  distributor: string;
  rToken: string;
  oracle: string;
  assetName: string;
  state: bigint;
  totalShares: bigint;
  totalAssetsUsdc: bigint;
  pricePerShareWad: bigint;
  idleUsdc: bigint;
  hedgedAssetsUsdc: bigint;
  longValueUsdc: bigint;
  shortEquityUsdc: bigint;
  currentGapBps: bigint;
  entryGapBps: bigint;
  hedgedNotionalUsdc: bigint;
  depositCap: bigint;
  minDeposit: bigint;
  perfFeeBps: bigint;
  targetLeverage: bigint;
  hwmAssetsPerShareWad: bigint;
  execFee: bigint;
  execFeeBalance: bigint;
  pendingOrderKey: string;
  pendingCreatedAt: bigint;
  fundingSettlePending: boolean;
  oraclePrice8: bigint;
  ammPrice8: bigint;
  pool: string;
  reservedClaimableUsdc: bigint;
  totalRedeemShares: bigint;
  settlingEpoch: bigint;
  settlingRemainingShares: bigint;
  gapCheckEnabled: boolean;
  maxPriceImpactBps: bigint;
  maxEntryPremiumBps: bigint;
  maxExitDiscountBps: bigint;
};

export interface IRYieldRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountAssets"
      | "ammPrice8"
      | "assetName"
      | "assetsOf"
      | "claimableAll"
      | "claimableUsdc"
      | "currentGapBps"
      | "depositCap"
      | "distributorOf"
      | "entryGapBps"
      | "execFee"
      | "execFeeBalance"
      | "factory"
      | "fundingSettlePending"
      | "fundingSharesOf"
      | "fundingSummary"
      | "gapCheckEnabled"
      | "hedgedAssetsUsdc"
      | "hedgedNotionalUsdc"
      | "hwmAssetsPerShareWad"
      | "idleUsdc"
      | "isRYieldVault"
      | "longRTokenBalance"
      | "longValueUsdc"
      | "marketIdOfVault"
      | "maxExitDiscountBps"
      | "maxPriceImpactBps"
      | "maxWithdrawableUsdc"
      | "minDeposit"
      | "oracle"
      | "owner"
      | "pendingCreatedAt"
      | "pendingOrderKey"
      | "perfFeeBps"
      | "pool"
      | "pricePerShareWad"
      | "rToken"
      | "redeemSharesOf"
      | "register"
      | "replaceVault"
      | "reservedClaimableUsdc"
      | "ryieldState"
      | "settlingEpoch"
      | "settlingRemainingShares"
      | "sharesOf"
      | "shortEquityUsdc"
      | "targetLeverage"
      | "totalAssetsUsdc"
      | "totalRedeemShares"
      | "totalShares"
      | "totalVaults"
      | "treasury"
      | "twapWindow"
      | "unregister"
      | "userSummary"
      | "vaultAccruedFundingGmx"
      | "vaultAt"
      | "vaultByRToken"
      | "vaultClaimableGmx"
      | "vaultOf"
      | "vaultSummary"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RYieldVaultRegistered"
      | "RYieldVaultReplaced"
      | "RYieldVaultUnregistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accountAssets",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ammPrice8",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assetName",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assetsOf",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAll",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableUsdc",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentGapBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorOf",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entryGapBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "execFee", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "execFeeBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundingSettlePending",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundingSharesOf",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundingSummary",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gapCheckEnabled",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hedgedAssetsUsdc",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hedgedNotionalUsdc",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hwmAssetsPerShareWad",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "idleUsdc", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isRYieldVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "longRTokenBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "longValueUsdc",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketIdOfVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxExitDiscountBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceImpactBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdrawableUsdc",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minDeposit",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pendingCreatedAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOrderKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "perfFeeBps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "pricePerShareWad",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "rToken", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "redeemSharesOf",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "replaceVault",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reservedClaimableUsdc",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ryieldState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlingEpoch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlingRemainingShares",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesOf",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shortEquityUsdc",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "targetLeverage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssetsUsdc",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRedeemShares",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "twapWindow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unregister",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userSummary",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultAccruedFundingGmx",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultByRToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultClaimableGmx",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "vaultOf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "vaultSummary",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ammPrice8", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetsOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentGapBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributorOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entryGapBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "execFeeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundingSettlePending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingSharesOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gapCheckEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hedgedAssetsUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hedgedNotionalUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hwmAssetsPerShareWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idleUsdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRYieldVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "longRTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "longValueUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketIdOfVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxExitDiscountBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceImpactBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdrawableUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingCreatedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingOrderKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "perfFeeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricePerShareWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemSharesOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "replaceVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservedClaimableUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ryieldState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlingEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlingRemainingShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharesOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shortEquityUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAssetsUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRedeemShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "twapWindow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unregister", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultAccruedFundingGmx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultByRToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultClaimableGmx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultSummary",
    data: BytesLike
  ): Result;
}

export namespace RYieldVaultRegisteredEvent {
  export type InputTuple = [
    marketId: BytesLike,
    vault: AddressLike,
    distributor: AddressLike,
    rToken: AddressLike
  ];
  export type OutputTuple = [
    marketId: string,
    vault: string,
    distributor: string,
    rToken: string
  ];
  export interface OutputObject {
    marketId: string;
    vault: string;
    distributor: string;
    rToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RYieldVaultReplacedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    oldVault: AddressLike,
    newVault: AddressLike,
    distributor: AddressLike,
    rToken: AddressLike
  ];
  export type OutputTuple = [
    marketId: string,
    oldVault: string,
    newVault: string,
    distributor: string,
    rToken: string
  ];
  export interface OutputObject {
    marketId: string;
    oldVault: string;
    newVault: string;
    distributor: string;
    rToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RYieldVaultUnregisteredEvent {
  export type InputTuple = [
    marketId: BytesLike,
    vault: AddressLike,
    rToken: AddressLike
  ];
  export type OutputTuple = [marketId: string, vault: string, rToken: string];
  export interface OutputObject {
    marketId: string;
    vault: string;
    rToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRYieldRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IRYieldRegistry;
  waitForDeployment(): Promise<this>;

  interface: IRYieldRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountAssets: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        depositedUsdc: bigint;
        hedgedUsdc: bigint;
        idleShareUsdc: bigint;
      }
    ],
    "view"
  >;

  ammPrice8: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  assetName: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  assetsOf: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  claimableAll: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        longConfirmed: bigint;
        longPending: bigint;
        shortConfirmed: bigint;
        shortPending: bigint;
        longAccrued: bigint;
        shortAccrued: bigint;
      }
    ],
    "view"
  >;

  claimableUsdc: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  currentGapBps: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  depositCap: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  distributorOf: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  entryGapBps: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  execFee: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  execFeeBalance: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  fundingSettlePending: TypedContractMethod<
    [marketId: BytesLike],
    [boolean],
    "view"
  >;

  fundingSharesOf: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  fundingSummary: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [RYieldFundingSummaryStructOutput],
    "view"
  >;

  gapCheckEnabled: TypedContractMethod<
    [marketId: BytesLike],
    [boolean],
    "view"
  >;

  hedgedAssetsUsdc: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  hedgedNotionalUsdc: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  hwmAssetsPerShareWad: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  idleUsdc: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  isRYieldVault: TypedContractMethod<[vault: AddressLike], [boolean], "view">;

  longRTokenBalance: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  longValueUsdc: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  marketIdOfVault: TypedContractMethod<[vault: AddressLike], [string], "view">;

  maxExitDiscountBps: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  maxPriceImpactBps: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  maxWithdrawableUsdc: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  minDeposit: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  oracle: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  owner: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  pendingCreatedAt: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  pendingOrderKey: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  perfFeeBps: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  pool: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  pricePerShareWad: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  rToken: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  redeemSharesOf: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  register: TypedContractMethod<
    [marketId: BytesLike, vault: AddressLike, distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  replaceVault: TypedContractMethod<
    [marketId: BytesLike, vault: AddressLike, distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  reservedClaimableUsdc: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  ryieldState: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  settlingEpoch: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  settlingRemainingShares: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  sharesOf: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  shortEquityUsdc: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  targetLeverage: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  totalAssetsUsdc: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  totalRedeemShares: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  totalShares: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  totalVaults: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  twapWindow: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  unregister: TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;

  userSummary: TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [RYieldUserSummaryStructOutput],
    "view"
  >;

  vaultAccruedFundingGmx: TypedContractMethod<
    [marketId: BytesLike],
    [[bigint, bigint] & { longAmount: bigint; shortAmount: bigint }],
    "view"
  >;

  vaultAt: TypedContractMethod<[index: BigNumberish], [string], "view">;

  vaultByRToken: TypedContractMethod<[rToken: AddressLike], [string], "view">;

  vaultClaimableGmx: TypedContractMethod<
    [marketId: BytesLike],
    [[bigint, bigint] & { longAmount: bigint; shortAmount: bigint }],
    "view"
  >;

  vaultOf: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  vaultSummary: TypedContractMethod<
    [marketId: BytesLike],
    [RYieldVaultSummaryStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountAssets"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        depositedUsdc: bigint;
        hedgedUsdc: bigint;
        idleShareUsdc: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ammPrice8"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "assetName"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "assetsOf"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimableAll"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        longConfirmed: bigint;
        longPending: bigint;
        shortConfirmed: bigint;
        shortPending: bigint;
        longAccrued: bigint;
        shortAccrued: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimableUsdc"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentGapBps"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositCap"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributorOf"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "entryGapBps"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "execFee"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "execFeeBalance"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundingSettlePending"
  ): TypedContractMethod<[marketId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "fundingSharesOf"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundingSummary"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [RYieldFundingSummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "gapCheckEnabled"
  ): TypedContractMethod<[marketId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hedgedAssetsUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hedgedNotionalUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hwmAssetsPerShareWad"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "idleUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRYieldVault"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "longRTokenBalance"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "longValueUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketIdOfVault"
  ): TypedContractMethod<[vault: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "maxExitDiscountBps"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxPriceImpactBps"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxWithdrawableUsdc"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "minDeposit"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "pendingCreatedAt"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingOrderKey"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "perfFeeBps"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "pricePerShareWad"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "rToken"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "redeemSharesOf"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [marketId: BytesLike, vault: AddressLike, distributor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "replaceVault"
  ): TypedContractMethod<
    [marketId: BytesLike, vault: AddressLike, distributor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reservedClaimableUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "ryieldState"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "settlingEpoch"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "settlingRemainingShares"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sharesOf"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "shortEquityUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "targetLeverage"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAssetsUsdc"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRedeemShares"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "twapWindow"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unregister"
  ): TypedContractMethod<[marketId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userSummary"
  ): TypedContractMethod<
    [marketId: BytesLike, user: AddressLike],
    [RYieldUserSummaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultAccruedFundingGmx"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [[bigint, bigint] & { longAmount: bigint; shortAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultAt"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "vaultByRToken"
  ): TypedContractMethod<[rToken: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "vaultClaimableGmx"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [[bigint, bigint] & { longAmount: bigint; shortAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "vaultOf"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "vaultSummary"
  ): TypedContractMethod<
    [marketId: BytesLike],
    [RYieldVaultSummaryStructOutput],
    "view"
  >;

  getEvent(
    key: "RYieldVaultRegistered"
  ): TypedContractEvent<
    RYieldVaultRegisteredEvent.InputTuple,
    RYieldVaultRegisteredEvent.OutputTuple,
    RYieldVaultRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RYieldVaultReplaced"
  ): TypedContractEvent<
    RYieldVaultReplacedEvent.InputTuple,
    RYieldVaultReplacedEvent.OutputTuple,
    RYieldVaultReplacedEvent.OutputObject
  >;
  getEvent(
    key: "RYieldVaultUnregistered"
  ): TypedContractEvent<
    RYieldVaultUnregisteredEvent.InputTuple,
    RYieldVaultUnregisteredEvent.OutputTuple,
    RYieldVaultUnregisteredEvent.OutputObject
  >;

  filters: {
    "RYieldVaultRegistered(bytes32,address,address,address)": TypedContractEvent<
      RYieldVaultRegisteredEvent.InputTuple,
      RYieldVaultRegisteredEvent.OutputTuple,
      RYieldVaultRegisteredEvent.OutputObject
    >;
    RYieldVaultRegistered: TypedContractEvent<
      RYieldVaultRegisteredEvent.InputTuple,
      RYieldVaultRegisteredEvent.OutputTuple,
      RYieldVaultRegisteredEvent.OutputObject
    >;

    "RYieldVaultReplaced(bytes32,address,address,address,address)": TypedContractEvent<
      RYieldVaultReplacedEvent.InputTuple,
      RYieldVaultReplacedEvent.OutputTuple,
      RYieldVaultReplacedEvent.OutputObject
    >;
    RYieldVaultReplaced: TypedContractEvent<
      RYieldVaultReplacedEvent.InputTuple,
      RYieldVaultReplacedEvent.OutputTuple,
      RYieldVaultReplacedEvent.OutputObject
    >;

    "RYieldVaultUnregistered(bytes32,address,address)": TypedContractEvent<
      RYieldVaultUnregisteredEvent.InputTuple,
      RYieldVaultUnregisteredEvent.OutputTuple,
      RYieldVaultUnregisteredEvent.OutputObject
    >;
    RYieldVaultUnregistered: TypedContractEvent<
      RYieldVaultUnregisteredEvent.InputTuple,
      RYieldVaultUnregisteredEvent.OutputTuple,
      RYieldVaultUnregisteredEvent.OutputObject
    >;
  };
}
