/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IUniswapV3Staker {
  export type IncentiveKeyStruct = {
    rewardToken: AddressLike;
    pool: AddressLike;
    startTime: BigNumberish;
    endTime: BigNumberish;
    refundee: AddressLike;
  };

  export type IncentiveKeyStructOutput = [
    rewardToken: string,
    pool: string,
    startTime: bigint,
    endTime: bigint,
    refundee: string
  ] & {
    rewardToken: string;
    pool: string;
    startTime: bigint;
    endTime: bigint;
    refundee: string;
  };
}

export interface IUniswapV3StakerInterface extends Interface {
  getFunction(
    nameOrSignature: "createIncentive" | "endIncentive"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createIncentive",
    values: [IUniswapV3Staker.IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endIncentive",
    values: [IUniswapV3Staker.IncentiveKeyStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "createIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endIncentive",
    data: BytesLike
  ): Result;
}

export interface IUniswapV3Staker extends BaseContract {
  connect(runner?: ContractRunner | null): IUniswapV3Staker;
  waitForDeployment(): Promise<this>;

  interface: IUniswapV3StakerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createIncentive: TypedContractMethod<
    [key: IUniswapV3Staker.IncentiveKeyStruct, reward: BigNumberish],
    [void],
    "nonpayable"
  >;

  endIncentive: TypedContractMethod<
    [key: IUniswapV3Staker.IncentiveKeyStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createIncentive"
  ): TypedContractMethod<
    [key: IUniswapV3Staker.IncentiveKeyStruct, reward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endIncentive"
  ): TypedContractMethod<
    [key: IUniswapV3Staker.IncentiveKeyStruct],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
