/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GmxPriceOracle__factory } from "./GmxPriceOracle__factory";
export { MockPriceOracle__factory } from "./MockPriceOracle__factory";
