/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RYieldVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PERF_FEE_BPS"
      | "assetName"
      | "assetsOf"
      | "deployToStrategy"
      | "deployed"
      | "deposit"
      | "depositCap"
      | "harvestFunding"
      | "idleAssets"
      | "lifetimePerfFee"
      | "lifetimeYield"
      | "marketId"
      | "owner"
      | "pricePerShare"
      | "pullFromStrategy"
      | "renounceOwnership"
      | "setDepositCap"
      | "setStrategy"
      | "sharesOf"
      | "strategy"
      | "totalAssets"
      | "totalShares"
      | "transferOwnership"
      | "treasury"
      | "usdc"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CapitalDeployed"
      | "CapitalPulled"
      | "DepositCapSet"
      | "Deposited"
      | "Harvested"
      | "OwnershipTransferred"
      | "StrategySet"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PERF_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assetName", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assetsOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployToStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deployed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "harvestFunding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "idleAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lifetimePerfFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lifetimeYield",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "marketId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pricePerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pullFromStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositCap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "strategy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PERF_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assetName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assetsOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployToStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "depositCap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "idleAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lifetimePerfFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lifetimeYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricePerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pullFromStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharesOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "strategy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CapitalDeployedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapitalPulledEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositCapSetEvent {
  export type InputTuple = [cap: BigNumberish];
  export type OutputTuple = [cap: bigint];
  export interface OutputObject {
    cap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    usdcIn: BigNumberish,
    sharesOut: BigNumberish
  ];
  export type OutputTuple = [user: string, usdcIn: bigint, sharesOut: bigint];
  export interface OutputObject {
    user: string;
    usdcIn: bigint;
    sharesOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestedEvent {
  export type InputTuple = [
    grossFundingUsdc: BigNumberish,
    perfFeeUsdc: BigNumberish,
    netToVault: BigNumberish
  ];
  export type OutputTuple = [
    grossFundingUsdc: bigint,
    perfFeeUsdc: bigint,
    netToVault: bigint
  ];
  export interface OutputObject {
    grossFundingUsdc: bigint;
    perfFeeUsdc: bigint;
    netToVault: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategySetEvent {
  export type InputTuple = [strategy: AddressLike];
  export type OutputTuple = [strategy: string];
  export interface OutputObject {
    strategy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    sharesIn: BigNumberish,
    usdcOut: BigNumberish
  ];
  export type OutputTuple = [user: string, sharesIn: bigint, usdcOut: bigint];
  export interface OutputObject {
    user: string;
    sharesIn: bigint;
    usdcOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RYieldVault extends BaseContract {
  connect(runner?: ContractRunner | null): RYieldVault;
  waitForDeployment(): Promise<this>;

  interface: RYieldVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PERF_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  assetName: TypedContractMethod<[], [string], "view">;

  assetsOf: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  deployToStrategy: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  depositCap: TypedContractMethod<[], [bigint], "view">;

  harvestFunding: TypedContractMethod<
    [grossFundingUsdc: BigNumberish],
    [void],
    "nonpayable"
  >;

  idleAssets: TypedContractMethod<[], [bigint], "view">;

  lifetimePerfFee: TypedContractMethod<[], [bigint], "view">;

  lifetimeYield: TypedContractMethod<[], [bigint], "view">;

  marketId: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pricePerShare: TypedContractMethod<[], [bigint], "view">;

  pullFromStrategy: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDepositCap: TypedContractMethod<[cap: BigNumberish], [void], "nonpayable">;

  setStrategy: TypedContractMethod<
    [strategy_: AddressLike],
    [void],
    "nonpayable"
  >;

  sharesOf: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  strategy: TypedContractMethod<[], [string], "view">;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[shares: BigNumberish], [bigint], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PERF_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assetName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assetsOf"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deployToStrategy"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deployed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "depositCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "harvestFunding"
  ): TypedContractMethod<
    [grossFundingUsdc: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "idleAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lifetimePerfFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lifetimeYield"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pricePerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pullFromStrategy"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositCap"
  ): TypedContractMethod<[cap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStrategy"
  ): TypedContractMethod<[strategy_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sharesOf"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "strategy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "nonpayable">;

  getEvent(
    key: "CapitalDeployed"
  ): TypedContractEvent<
    CapitalDeployedEvent.InputTuple,
    CapitalDeployedEvent.OutputTuple,
    CapitalDeployedEvent.OutputObject
  >;
  getEvent(
    key: "CapitalPulled"
  ): TypedContractEvent<
    CapitalPulledEvent.InputTuple,
    CapitalPulledEvent.OutputTuple,
    CapitalPulledEvent.OutputObject
  >;
  getEvent(
    key: "DepositCapSet"
  ): TypedContractEvent<
    DepositCapSetEvent.InputTuple,
    DepositCapSetEvent.OutputTuple,
    DepositCapSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Harvested"
  ): TypedContractEvent<
    HarvestedEvent.InputTuple,
    HarvestedEvent.OutputTuple,
    HarvestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StrategySet"
  ): TypedContractEvent<
    StrategySetEvent.InputTuple,
    StrategySetEvent.OutputTuple,
    StrategySetEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "CapitalDeployed(uint256)": TypedContractEvent<
      CapitalDeployedEvent.InputTuple,
      CapitalDeployedEvent.OutputTuple,
      CapitalDeployedEvent.OutputObject
    >;
    CapitalDeployed: TypedContractEvent<
      CapitalDeployedEvent.InputTuple,
      CapitalDeployedEvent.OutputTuple,
      CapitalDeployedEvent.OutputObject
    >;

    "CapitalPulled(uint256)": TypedContractEvent<
      CapitalPulledEvent.InputTuple,
      CapitalPulledEvent.OutputTuple,
      CapitalPulledEvent.OutputObject
    >;
    CapitalPulled: TypedContractEvent<
      CapitalPulledEvent.InputTuple,
      CapitalPulledEvent.OutputTuple,
      CapitalPulledEvent.OutputObject
    >;

    "DepositCapSet(uint256)": TypedContractEvent<
      DepositCapSetEvent.InputTuple,
      DepositCapSetEvent.OutputTuple,
      DepositCapSetEvent.OutputObject
    >;
    DepositCapSet: TypedContractEvent<
      DepositCapSetEvent.InputTuple,
      DepositCapSetEvent.OutputTuple,
      DepositCapSetEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Harvested(uint256,uint256,uint256)": TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;
    Harvested: TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StrategySet(address)": TypedContractEvent<
      StrategySetEvent.InputTuple,
      StrategySetEvent.OutputTuple,
      StrategySetEvent.OutputObject
    >;
    StrategySet: TypedContractEvent<
      StrategySetEvent.InputTuple,
      StrategySetEvent.OutputTuple,
      StrategySetEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
