/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface DebtSettlerInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "LiquidationDebtSettled"): EventFragment;
}

export namespace LiquidationDebtSettledEvent {
  export type InputTuple = [
    vault: AddressLike,
    earmarkedRToken: BigNumberish,
    earmarkedUsdc: BigNumberish,
    ownerBurned: BigNumberish,
    badDebtRToken: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    earmarkedRToken: bigint,
    earmarkedUsdc: bigint,
    ownerBurned: bigint,
    badDebtRToken: bigint
  ];
  export interface OutputObject {
    vault: string;
    earmarkedRToken: bigint;
    earmarkedUsdc: bigint;
    ownerBurned: bigint;
    badDebtRToken: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DebtSettler extends BaseContract {
  connect(runner?: ContractRunner | null): DebtSettler;
  waitForDeployment(): Promise<this>;

  interface: DebtSettlerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "LiquidationDebtSettled"
  ): TypedContractEvent<
    LiquidationDebtSettledEvent.InputTuple,
    LiquidationDebtSettledEvent.OutputTuple,
    LiquidationDebtSettledEvent.OutputObject
  >;

  filters: {
    "LiquidationDebtSettled(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LiquidationDebtSettledEvent.InputTuple,
      LiquidationDebtSettledEvent.OutputTuple,
      LiquidationDebtSettledEvent.OutputObject
    >;
    LiquidationDebtSettled: TypedContractEvent<
      LiquidationDebtSettledEvent.InputTuple,
      LiquidationDebtSettledEvent.OutputTuple,
      LiquidationDebtSettledEvent.OutputObject
    >;
  };
}
