/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface VaultSettleInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "BadDebt"
      | "CollateralDepositedToPosition"
      | "CollateralWithdrawn"
      | "CollateralWithdrawnFromPosition"
      | "FeesSettled"
      | "Liquidated"
      | "PositionOpenFailed"
      | "PositionOpened"
      | "Redeemed"
  ): EventFragment;
}

export namespace BadDebtEvent {
  export type InputTuple = [vault: AddressLike, shortfallUsdc: BigNumberish];
  export type OutputTuple = [vault: string, shortfallUsdc: bigint];
  export interface OutputObject {
    vault: string;
    shortfallUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralDepositedToPositionEvent {
  export type InputTuple = [vault: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [vault: string, usdcAmount: bigint];
  export interface OutputObject {
    vault: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralWithdrawnEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralWithdrawnFromPositionEvent {
  export type InputTuple = [vault: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [vault: string, usdcAmount: bigint];
  export interface OutputObject {
    vault: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesSettledEvent {
  export type InputTuple = [vault: AddressLike, toTreasuryUsdc: BigNumberish];
  export type OutputTuple = [vault: string, toTreasuryUsdc: bigint];
  export interface OutputObject {
    vault: string;
    toTreasuryUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    debtRepaidUsdc: BigNumberish,
    refundUsdc: BigNumberish,
    keeperBountyUsdc: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    debtRepaidUsdc: bigint,
    refundUsdc: bigint,
    keeperBountyUsdc: bigint
  ];
  export interface OutputObject {
    vault: string;
    debtRepaidUsdc: bigint;
    refundUsdc: bigint;
    keeperBountyUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenFailedEvent {
  export type InputTuple = [vault: AddressLike, orderKey: BytesLike];
  export type OutputTuple = [vault: string, orderKey: string];
  export interface OutputObject {
    vault: string;
    orderKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [vault: AddressLike, posKey: BytesLike];
  export type OutputTuple = [vault: string, posKey: string];
  export interface OutputObject {
    vault: string;
    posKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    vault: AddressLike,
    redeemer: AddressLike,
    rTokenAmount: BigNumberish,
    usdcOut: BigNumberish,
    feeUsdc: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    redeemer: string,
    rTokenAmount: bigint,
    usdcOut: bigint,
    feeUsdc: bigint
  ];
  export interface OutputObject {
    vault: string;
    redeemer: string;
    rTokenAmount: bigint;
    usdcOut: bigint;
    feeUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultSettle extends BaseContract {
  connect(runner?: ContractRunner | null): VaultSettle;
  waitForDeployment(): Promise<this>;

  interface: VaultSettleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "BadDebt"
  ): TypedContractEvent<
    BadDebtEvent.InputTuple,
    BadDebtEvent.OutputTuple,
    BadDebtEvent.OutputObject
  >;
  getEvent(
    key: "CollateralDepositedToPosition"
  ): TypedContractEvent<
    CollateralDepositedToPositionEvent.InputTuple,
    CollateralDepositedToPositionEvent.OutputTuple,
    CollateralDepositedToPositionEvent.OutputObject
  >;
  getEvent(
    key: "CollateralWithdrawn"
  ): TypedContractEvent<
    CollateralWithdrawnEvent.InputTuple,
    CollateralWithdrawnEvent.OutputTuple,
    CollateralWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "CollateralWithdrawnFromPosition"
  ): TypedContractEvent<
    CollateralWithdrawnFromPositionEvent.InputTuple,
    CollateralWithdrawnFromPositionEvent.OutputTuple,
    CollateralWithdrawnFromPositionEvent.OutputObject
  >;
  getEvent(
    key: "FeesSettled"
  ): TypedContractEvent<
    FeesSettledEvent.InputTuple,
    FeesSettledEvent.OutputTuple,
    FeesSettledEvent.OutputObject
  >;
  getEvent(
    key: "Liquidated"
  ): TypedContractEvent<
    LiquidatedEvent.InputTuple,
    LiquidatedEvent.OutputTuple,
    LiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpenFailed"
  ): TypedContractEvent<
    PositionOpenFailedEvent.InputTuple,
    PositionOpenFailedEvent.OutputTuple,
    PositionOpenFailedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;

  filters: {
    "BadDebt(address,uint256)": TypedContractEvent<
      BadDebtEvent.InputTuple,
      BadDebtEvent.OutputTuple,
      BadDebtEvent.OutputObject
    >;
    BadDebt: TypedContractEvent<
      BadDebtEvent.InputTuple,
      BadDebtEvent.OutputTuple,
      BadDebtEvent.OutputObject
    >;

    "CollateralDepositedToPosition(address,uint256)": TypedContractEvent<
      CollateralDepositedToPositionEvent.InputTuple,
      CollateralDepositedToPositionEvent.OutputTuple,
      CollateralDepositedToPositionEvent.OutputObject
    >;
    CollateralDepositedToPosition: TypedContractEvent<
      CollateralDepositedToPositionEvent.InputTuple,
      CollateralDepositedToPositionEvent.OutputTuple,
      CollateralDepositedToPositionEvent.OutputObject
    >;

    "CollateralWithdrawn(address,uint256)": TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;
    CollateralWithdrawn: TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;

    "CollateralWithdrawnFromPosition(address,uint256)": TypedContractEvent<
      CollateralWithdrawnFromPositionEvent.InputTuple,
      CollateralWithdrawnFromPositionEvent.OutputTuple,
      CollateralWithdrawnFromPositionEvent.OutputObject
    >;
    CollateralWithdrawnFromPosition: TypedContractEvent<
      CollateralWithdrawnFromPositionEvent.InputTuple,
      CollateralWithdrawnFromPositionEvent.OutputTuple,
      CollateralWithdrawnFromPositionEvent.OutputObject
    >;

    "FeesSettled(address,uint256)": TypedContractEvent<
      FeesSettledEvent.InputTuple,
      FeesSettledEvent.OutputTuple,
      FeesSettledEvent.OutputObject
    >;
    FeesSettled: TypedContractEvent<
      FeesSettledEvent.InputTuple,
      FeesSettledEvent.OutputTuple,
      FeesSettledEvent.OutputObject
    >;

    "Liquidated(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;
    Liquidated: TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;

    "PositionOpenFailed(address,bytes32)": TypedContractEvent<
      PositionOpenFailedEvent.InputTuple,
      PositionOpenFailedEvent.OutputTuple,
      PositionOpenFailedEvent.OutputObject
    >;
    PositionOpenFailed: TypedContractEvent<
      PositionOpenFailedEvent.InputTuple,
      PositionOpenFailedEvent.OutputTuple,
      PositionOpenFailedEvent.OutputObject
    >;

    "PositionOpened(address,bytes32)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;

    "Redeemed(address,address,uint256,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
  };
}
