/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type RiskParamsStruct = {
  maxLtv1xBps: BigNumberish;
  bufferBps: BigNumberish;
  maxLtvAtMaxLevBps: BigNumberish;
  flatTier: BigNumberish;
  maxLeverage: BigNumberish;
};

export type RiskParamsStructOutput = [
  maxLtv1xBps: bigint,
  bufferBps: bigint,
  maxLtvAtMaxLevBps: bigint,
  flatTier: bigint,
  maxLeverage: bigint
] & {
  maxLtv1xBps: bigint;
  bufferBps: bigint;
  maxLtvAtMaxLevBps: bigint;
  flatTier: bigint;
  maxLeverage: bigint;
};

export type VaultGmxPositionStruct = {
  exists: boolean;
  sizeInUsd: BigNumberish;
  collateralAmount: BigNumberish;
  entryPrice8: BigNumberish;
};

export type VaultGmxPositionStructOutput = [
  exists: boolean,
  sizeInUsd: bigint,
  collateralAmount: bigint,
  entryPrice8: bigint
] & {
  exists: boolean;
  sizeInUsd: bigint;
  collateralAmount: bigint;
  entryPrice8: bigint;
};

export type VaultSnapshotStruct = {
  owner: AddressLike;
  marketId: BytesLike;
  state: BigNumberish;
  leverage: BigNumberish;
  isLong: boolean;
  posKey: BytesLike;
  collateralUsdc: BigNumberish;
  debtRToken: BigNumberish;
  pendingKind: BigNumberish;
  pendingOrderKey: BytesLike;
  pendingCreatedAt: BigNumberish;
  maxLtv1xBps: BigNumberish;
  bufferBps: BigNumberish;
  maxLtvAtMaxLevBps: BigNumberish;
  flatTier: BigNumberish;
  maxLeverage: BigNumberish;
  collateralValueUsdWad: BigNumberish;
  debtValueUsdWad: BigNumberish;
  currentLtvBps: BigNumberish;
  healthFactorWad: BigNumberish;
  lltvBps: BigNumberish;
  rltBps: BigNumberish;
  effectiveMaxLtvBps: BigNumberish;
  oraclePrice8: BigNumberish;
  pendingFeesUsdc: BigNumberish;
  isRedeemable: boolean;
  isLiquidatable: boolean;
  tpOrderKey: BytesLike;
  slOrderKey: BytesLike;
  gmx: VaultGmxPositionStruct;
};

export type VaultSnapshotStructOutput = [
  owner: string,
  marketId: string,
  state: bigint,
  leverage: bigint,
  isLong: boolean,
  posKey: string,
  collateralUsdc: bigint,
  debtRToken: bigint,
  pendingKind: bigint,
  pendingOrderKey: string,
  pendingCreatedAt: bigint,
  maxLtv1xBps: bigint,
  bufferBps: bigint,
  maxLtvAtMaxLevBps: bigint,
  flatTier: bigint,
  maxLeverage: bigint,
  collateralValueUsdWad: bigint,
  debtValueUsdWad: bigint,
  currentLtvBps: bigint,
  healthFactorWad: bigint,
  lltvBps: bigint,
  rltBps: bigint,
  effectiveMaxLtvBps: bigint,
  oraclePrice8: bigint,
  pendingFeesUsdc: bigint,
  isRedeemable: boolean,
  isLiquidatable: boolean,
  tpOrderKey: string,
  slOrderKey: string,
  gmx: VaultGmxPositionStructOutput
] & {
  owner: string;
  marketId: string;
  state: bigint;
  leverage: bigint;
  isLong: boolean;
  posKey: string;
  collateralUsdc: bigint;
  debtRToken: bigint;
  pendingKind: bigint;
  pendingOrderKey: string;
  pendingCreatedAt: bigint;
  maxLtv1xBps: bigint;
  bufferBps: bigint;
  maxLtvAtMaxLevBps: bigint;
  flatTier: bigint;
  maxLeverage: bigint;
  collateralValueUsdWad: bigint;
  debtValueUsdWad: bigint;
  currentLtvBps: bigint;
  healthFactorWad: bigint;
  lltvBps: bigint;
  rltBps: bigint;
  effectiveMaxLtvBps: bigint;
  oraclePrice8: bigint;
  pendingFeesUsdc: bigint;
  isRedeemable: boolean;
  isLiquidatable: boolean;
  tpOrderKey: string;
  slOrderKey: string;
  gmx: VaultGmxPositionStructOutput;
};

export declare namespace IGmxAdapter {
  export type GmxPositionDataStruct = {
    exists: boolean;
    sizeInUsd: BigNumberish;
    collateralAmount: BigNumberish;
    entryPrice8: BigNumberish;
  };

  export type GmxPositionDataStructOutput = [
    exists: boolean,
    sizeInUsd: bigint,
    collateralAmount: bigint,
    entryPrice8: bigint
  ] & {
    exists: boolean;
    sizeInUsd: bigint;
    collateralAmount: bigint;
    entryPrice8: bigint;
  };
}

export interface PositionVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accruedFeesUsdc"
      | "afterOrderCancellation"
      | "afterOrderExecution"
      | "bufferBps"
      | "cancelLimitOrder"
      | "cancelStopLoss"
      | "cancelStuckOrder"
      | "cancelTakeProfit"
      | "closePosition"
      | "collateral"
      | "collateralValueUsdWad"
      | "currentLTV"
      | "debt"
      | "debtValueUsdWad"
      | "deposit"
      | "effectiveMaxLtvBps"
      | "factory"
      | "flatTier"
      | "gmx"
      | "gmxPosition"
      | "healthFactor"
      | "initialize"
      | "isLong"
      | "isRedeemable"
      | "lastAccrual"
      | "leverage"
      | "liquidate"
      | "liquidator"
      | "lltvBps"
      | "marketId"
      | "maxLeverage"
      | "maxLtv1xBps"
      | "maxLtvAtMaxLevBps"
      | "mint"
      | "openLimitPosition"
      | "openPosition"
      | "oracle"
      | "owner"
      | "pending"
      | "pendingFeesUsdc"
      | "pendingRedeemAmt"
      | "pendingRedeemUsdcSnap"
      | "pendingRedeemer"
      | "posKey"
      | "rToken"
      | "redeem"
      | "repay"
      | "rltBps"
      | "setStopLoss"
      | "setTakeProfit"
      | "slOrderKey"
      | "state"
      | "tpOrderKey"
      | "usdc"
      | "vaultInfo"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BadDebt"
      | "Closed"
      | "CollateralDeposited"
      | "CollateralWithdrawn"
      | "ConditionalOrderCancelled"
      | "FeesSettled"
      | "Initialized"
      | "Liquidated"
      | "PositionCloseRequested"
      | "PositionOpenFailed"
      | "PositionOpenRequested"
      | "PositionOpened"
      | "RBTCMinted"
      | "RBTCRepaid"
      | "RedeemRequested"
      | "Redeemed"
      | "StopLossSet"
      | "StuckOrderRecovered"
      | "TakeProfitSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accruedFeesUsdc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "afterOrderCancellation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "afterOrderExecution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "bufferBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelLimitOrder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStopLoss",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelStuckOrder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTakeProfit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralValueUsdWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentLTV",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "debt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "debtValueUsdWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "effectiveMaxLtvBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "flatTier", values?: undefined): string;
  encodeFunctionData(functionFragment: "gmx", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gmxPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "healthFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      RiskParamsStruct
    ]
  ): string;
  encodeFunctionData(functionFragment: "isLong", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isRedeemable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastAccrual",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "leverage", values?: undefined): string;
  encodeFunctionData(functionFragment: "liquidate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lltvBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "marketId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxLeverage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLtv1xBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxLtvAtMaxLevBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mint", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "openLimitPosition",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "openPosition",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pending", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingFeesUsdc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedeemAmt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedeemUsdcSnap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedeemer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "posKey", values?: undefined): string;
  encodeFunctionData(functionFragment: "rToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "repay", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "rltBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setStopLoss",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTakeProfit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slOrderKey",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tpOrderKey",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(functionFragment: "vaultInfo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "accruedFeesUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterOrderCancellation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterOrderExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bufferBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStopLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelStuckOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTakeProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "collateral", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralValueUsdWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentLTV", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "debt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "debtValueUsdWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "effectiveMaxLtvBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flatTier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gmx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gmxPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "healthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isLong", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRedeemable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastAccrual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leverage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liquidator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lltvBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "marketId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLtv1xBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxLtvAtMaxLevBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openLimitPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pending", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingFeesUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedeemAmt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedeemUsdcSnap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedeemer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "posKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rltBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStopLoss",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTakeProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slOrderKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tpOrderKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaultInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BadDebtEvent {
  export type InputTuple = [vault: AddressLike, shortfallUsdc: BigNumberish];
  export type OutputTuple = [vault: string, shortfallUsdc: bigint];
  export interface OutputObject {
    vault: string;
    shortfallUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClosedEvent {
  export type InputTuple = [vault: AddressLike, returned: BigNumberish];
  export type OutputTuple = [vault: string, returned: bigint];
  export interface OutputObject {
    vault: string;
    returned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralDepositedEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollateralWithdrawnEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionalOrderCancelledEvent {
  export type InputTuple = [
    vault: AddressLike,
    orderKey: BytesLike,
    kind: BigNumberish
  ];
  export type OutputTuple = [vault: string, orderKey: string, kind: bigint];
  export interface OutputObject {
    vault: string;
    orderKey: string;
    kind: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesSettledEvent {
  export type InputTuple = [vault: AddressLike, toTreasuryUsdc: BigNumberish];
  export type OutputTuple = [vault: string, toTreasuryUsdc: bigint];
  export interface OutputObject {
    vault: string;
    toTreasuryUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidatedEvent {
  export type InputTuple = [
    vault: AddressLike,
    debtRepaidUsdc: BigNumberish,
    refundUsdc: BigNumberish,
    keeperBountyUsdc: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    debtRepaidUsdc: bigint,
    refundUsdc: bigint,
    keeperBountyUsdc: bigint
  ];
  export interface OutputObject {
    vault: string;
    debtRepaidUsdc: bigint;
    refundUsdc: bigint;
    keeperBountyUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionCloseRequestedEvent {
  export type InputTuple = [
    vault: AddressLike,
    orderKey: BytesLike,
    kind: BigNumberish
  ];
  export type OutputTuple = [vault: string, orderKey: string, kind: bigint];
  export interface OutputObject {
    vault: string;
    orderKey: string;
    kind: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenFailedEvent {
  export type InputTuple = [vault: AddressLike, orderKey: BytesLike];
  export type OutputTuple = [vault: string, orderKey: string];
  export interface OutputObject {
    vault: string;
    orderKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenRequestedEvent {
  export type InputTuple = [
    vault: AddressLike,
    orderKey: BytesLike,
    leverage: BigNumberish,
    isLong: boolean
  ];
  export type OutputTuple = [
    vault: string,
    orderKey: string,
    leverage: bigint,
    isLong: boolean
  ];
  export interface OutputObject {
    vault: string;
    orderKey: string;
    leverage: bigint;
    isLong: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [vault: AddressLike, posKey: BytesLike];
  export type OutputTuple = [vault: string, posKey: string];
  export interface OutputObject {
    vault: string;
    posKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RBTCMintedEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RBTCRepaidEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemRequestedEvent {
  export type InputTuple = [
    vault: AddressLike,
    redeemer: AddressLike,
    orderKey: BytesLike,
    rTokenAmount: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    redeemer: string,
    orderKey: string,
    rTokenAmount: bigint
  ];
  export interface OutputObject {
    vault: string;
    redeemer: string;
    orderKey: string;
    rTokenAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedEvent {
  export type InputTuple = [
    vault: AddressLike,
    redeemer: AddressLike,
    rTokenAmount: BigNumberish,
    usdcOut: BigNumberish,
    feeUsdc: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    redeemer: string,
    rTokenAmount: bigint,
    usdcOut: bigint,
    feeUsdc: bigint
  ];
  export interface OutputObject {
    vault: string;
    redeemer: string;
    rTokenAmount: bigint;
    usdcOut: bigint;
    feeUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StopLossSetEvent {
  export type InputTuple = [
    vault: AddressLike,
    orderKey: BytesLike,
    triggerPrice8: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    orderKey: string,
    triggerPrice8: bigint
  ];
  export interface OutputObject {
    vault: string;
    orderKey: string;
    triggerPrice8: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StuckOrderRecoveredEvent {
  export type InputTuple = [vault: AddressLike, orderKey: BytesLike];
  export type OutputTuple = [vault: string, orderKey: string];
  export interface OutputObject {
    vault: string;
    orderKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TakeProfitSetEvent {
  export type InputTuple = [
    vault: AddressLike,
    orderKey: BytesLike,
    triggerPrice8: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    orderKey: string,
    triggerPrice8: bigint
  ];
  export interface OutputObject {
    vault: string;
    orderKey: string;
    triggerPrice8: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PositionVault extends BaseContract {
  connect(runner?: ContractRunner | null): PositionVault;
  waitForDeployment(): Promise<this>;

  interface: PositionVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accruedFeesUsdc: TypedContractMethod<[], [bigint], "view">;

  afterOrderCancellation: TypedContractMethod<
    [orderKey: BytesLike],
    [void],
    "nonpayable"
  >;

  afterOrderExecution: TypedContractMethod<
    [orderKey: BytesLike],
    [void],
    "nonpayable"
  >;

  bufferBps: TypedContractMethod<[], [bigint], "view">;

  cancelLimitOrder: TypedContractMethod<[], [void], "nonpayable">;

  cancelStopLoss: TypedContractMethod<[], [void], "nonpayable">;

  cancelStuckOrder: TypedContractMethod<[], [void], "nonpayable">;

  cancelTakeProfit: TypedContractMethod<[], [void], "nonpayable">;

  closePosition: TypedContractMethod<[], [void], "payable">;

  collateral: TypedContractMethod<[], [bigint], "view">;

  collateralValueUsdWad: TypedContractMethod<[], [bigint], "view">;

  currentLTV: TypedContractMethod<[], [bigint], "view">;

  debt: TypedContractMethod<[], [bigint], "view">;

  debtValueUsdWad: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  effectiveMaxLtvBps: TypedContractMethod<[], [bigint], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  flatTier: TypedContractMethod<[], [bigint], "view">;

  gmx: TypedContractMethod<[], [string], "view">;

  gmxPosition: TypedContractMethod<
    [],
    [IGmxAdapter.GmxPositionDataStructOutput],
    "view"
  >;

  healthFactor: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [
      owner_: AddressLike,
      factory_: AddressLike,
      gmx_: AddressLike,
      oracle_: AddressLike,
      usdc_: AddressLike,
      rToken_: AddressLike,
      marketId_: BytesLike,
      risk: RiskParamsStruct
    ],
    [void],
    "nonpayable"
  >;

  isLong: TypedContractMethod<[], [boolean], "view">;

  isRedeemable: TypedContractMethod<[], [boolean], "view">;

  lastAccrual: TypedContractMethod<[], [bigint], "view">;

  leverage: TypedContractMethod<[], [bigint], "view">;

  liquidate: TypedContractMethod<[], [void], "payable">;

  liquidator: TypedContractMethod<[], [string], "view">;

  lltvBps: TypedContractMethod<[], [bigint], "view">;

  marketId: TypedContractMethod<[], [string], "view">;

  maxLeverage: TypedContractMethod<[], [bigint], "view">;

  maxLtv1xBps: TypedContractMethod<[], [bigint], "view">;

  maxLtvAtMaxLevBps: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<[rBtcAmount: BigNumberish], [void], "nonpayable">;

  openLimitPosition: TypedContractMethod<
    [leverage_: BigNumberish, triggerPrice8: BigNumberish, isLong_: boolean],
    [void],
    "payable"
  >;

  openPosition: TypedContractMethod<
    [leverage_: BigNumberish, isLong_: boolean],
    [void],
    "payable"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pending: TypedContractMethod<
    [],
    [
      [bigint, string, bigint] & {
        kind: bigint;
        orderKey: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  pendingFeesUsdc: TypedContractMethod<[], [bigint], "view">;

  pendingRedeemAmt: TypedContractMethod<[], [bigint], "view">;

  pendingRedeemUsdcSnap: TypedContractMethod<[], [bigint], "view">;

  pendingRedeemer: TypedContractMethod<[], [string], "view">;

  posKey: TypedContractMethod<[], [string], "view">;

  rToken: TypedContractMethod<[], [string], "view">;

  redeem: TypedContractMethod<[rTokenAmount: BigNumberish], [void], "payable">;

  repay: TypedContractMethod<[rBtcAmount: BigNumberish], [void], "nonpayable">;

  rltBps: TypedContractMethod<[], [bigint], "view">;

  setStopLoss: TypedContractMethod<
    [triggerPrice8: BigNumberish],
    [void],
    "payable"
  >;

  setTakeProfit: TypedContractMethod<
    [triggerPrice8: BigNumberish],
    [void],
    "payable"
  >;

  slOrderKey: TypedContractMethod<[], [string], "view">;

  state: TypedContractMethod<[], [bigint], "view">;

  tpOrderKey: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  vaultInfo: TypedContractMethod<[], [VaultSnapshotStructOutput], "view">;

  withdraw: TypedContractMethod<
    [usdcAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accruedFeesUsdc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "afterOrderCancellation"
  ): TypedContractMethod<[orderKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "afterOrderExecution"
  ): TypedContractMethod<[orderKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bufferBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelLimitOrder"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelStopLoss"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelStuckOrder"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTakeProfit"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "collateral"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "collateralValueUsdWad"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentLTV"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "debt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "debtValueUsdWad"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "effectiveMaxLtvBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "flatTier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gmx"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gmxPosition"
  ): TypedContractMethod<[], [IGmxAdapter.GmxPositionDataStructOutput], "view">;
  getFunction(
    nameOrSignature: "healthFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      owner_: AddressLike,
      factory_: AddressLike,
      gmx_: AddressLike,
      oracle_: AddressLike,
      usdc_: AddressLike,
      rToken_: AddressLike,
      marketId_: BytesLike,
      risk: RiskParamsStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isLong"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRedeemable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastAccrual"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "leverage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "liquidator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lltvBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxLeverage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxLtv1xBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxLtvAtMaxLevBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<[rBtcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "openLimitPosition"
  ): TypedContractMethod<
    [leverage_: BigNumberish, triggerPrice8: BigNumberish, isLong_: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "openPosition"
  ): TypedContractMethod<
    [leverage_: BigNumberish, isLong_: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pending"
  ): TypedContractMethod<
    [],
    [
      [bigint, string, bigint] & {
        kind: bigint;
        orderKey: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingFeesUsdc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingRedeemAmt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingRedeemUsdcSnap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingRedeemer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "posKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[rTokenAmount: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[rBtcAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rltBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setStopLoss"
  ): TypedContractMethod<[triggerPrice8: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "setTakeProfit"
  ): TypedContractMethod<[triggerPrice8: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "slOrderKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tpOrderKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultInfo"
  ): TypedContractMethod<[], [VaultSnapshotStructOutput], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[usdcAmount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BadDebt"
  ): TypedContractEvent<
    BadDebtEvent.InputTuple,
    BadDebtEvent.OutputTuple,
    BadDebtEvent.OutputObject
  >;
  getEvent(
    key: "Closed"
  ): TypedContractEvent<
    ClosedEvent.InputTuple,
    ClosedEvent.OutputTuple,
    ClosedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralDeposited"
  ): TypedContractEvent<
    CollateralDepositedEvent.InputTuple,
    CollateralDepositedEvent.OutputTuple,
    CollateralDepositedEvent.OutputObject
  >;
  getEvent(
    key: "CollateralWithdrawn"
  ): TypedContractEvent<
    CollateralWithdrawnEvent.InputTuple,
    CollateralWithdrawnEvent.OutputTuple,
    CollateralWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ConditionalOrderCancelled"
  ): TypedContractEvent<
    ConditionalOrderCancelledEvent.InputTuple,
    ConditionalOrderCancelledEvent.OutputTuple,
    ConditionalOrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "FeesSettled"
  ): TypedContractEvent<
    FeesSettledEvent.InputTuple,
    FeesSettledEvent.OutputTuple,
    FeesSettledEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Liquidated"
  ): TypedContractEvent<
    LiquidatedEvent.InputTuple,
    LiquidatedEvent.OutputTuple,
    LiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "PositionCloseRequested"
  ): TypedContractEvent<
    PositionCloseRequestedEvent.InputTuple,
    PositionCloseRequestedEvent.OutputTuple,
    PositionCloseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpenFailed"
  ): TypedContractEvent<
    PositionOpenFailedEvent.InputTuple,
    PositionOpenFailedEvent.OutputTuple,
    PositionOpenFailedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpenRequested"
  ): TypedContractEvent<
    PositionOpenRequestedEvent.InputTuple,
    PositionOpenRequestedEvent.OutputTuple,
    PositionOpenRequestedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "RBTCMinted"
  ): TypedContractEvent<
    RBTCMintedEvent.InputTuple,
    RBTCMintedEvent.OutputTuple,
    RBTCMintedEvent.OutputObject
  >;
  getEvent(
    key: "RBTCRepaid"
  ): TypedContractEvent<
    RBTCRepaidEvent.InputTuple,
    RBTCRepaidEvent.OutputTuple,
    RBTCRepaidEvent.OutputObject
  >;
  getEvent(
    key: "RedeemRequested"
  ): TypedContractEvent<
    RedeemRequestedEvent.InputTuple,
    RedeemRequestedEvent.OutputTuple,
    RedeemRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Redeemed"
  ): TypedContractEvent<
    RedeemedEvent.InputTuple,
    RedeemedEvent.OutputTuple,
    RedeemedEvent.OutputObject
  >;
  getEvent(
    key: "StopLossSet"
  ): TypedContractEvent<
    StopLossSetEvent.InputTuple,
    StopLossSetEvent.OutputTuple,
    StopLossSetEvent.OutputObject
  >;
  getEvent(
    key: "StuckOrderRecovered"
  ): TypedContractEvent<
    StuckOrderRecoveredEvent.InputTuple,
    StuckOrderRecoveredEvent.OutputTuple,
    StuckOrderRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "TakeProfitSet"
  ): TypedContractEvent<
    TakeProfitSetEvent.InputTuple,
    TakeProfitSetEvent.OutputTuple,
    TakeProfitSetEvent.OutputObject
  >;

  filters: {
    "BadDebt(address,uint256)": TypedContractEvent<
      BadDebtEvent.InputTuple,
      BadDebtEvent.OutputTuple,
      BadDebtEvent.OutputObject
    >;
    BadDebt: TypedContractEvent<
      BadDebtEvent.InputTuple,
      BadDebtEvent.OutputTuple,
      BadDebtEvent.OutputObject
    >;

    "Closed(address,uint256)": TypedContractEvent<
      ClosedEvent.InputTuple,
      ClosedEvent.OutputTuple,
      ClosedEvent.OutputObject
    >;
    Closed: TypedContractEvent<
      ClosedEvent.InputTuple,
      ClosedEvent.OutputTuple,
      ClosedEvent.OutputObject
    >;

    "CollateralDeposited(address,uint256)": TypedContractEvent<
      CollateralDepositedEvent.InputTuple,
      CollateralDepositedEvent.OutputTuple,
      CollateralDepositedEvent.OutputObject
    >;
    CollateralDeposited: TypedContractEvent<
      CollateralDepositedEvent.InputTuple,
      CollateralDepositedEvent.OutputTuple,
      CollateralDepositedEvent.OutputObject
    >;

    "CollateralWithdrawn(address,uint256)": TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;
    CollateralWithdrawn: TypedContractEvent<
      CollateralWithdrawnEvent.InputTuple,
      CollateralWithdrawnEvent.OutputTuple,
      CollateralWithdrawnEvent.OutputObject
    >;

    "ConditionalOrderCancelled(address,bytes32,uint8)": TypedContractEvent<
      ConditionalOrderCancelledEvent.InputTuple,
      ConditionalOrderCancelledEvent.OutputTuple,
      ConditionalOrderCancelledEvent.OutputObject
    >;
    ConditionalOrderCancelled: TypedContractEvent<
      ConditionalOrderCancelledEvent.InputTuple,
      ConditionalOrderCancelledEvent.OutputTuple,
      ConditionalOrderCancelledEvent.OutputObject
    >;

    "FeesSettled(address,uint256)": TypedContractEvent<
      FeesSettledEvent.InputTuple,
      FeesSettledEvent.OutputTuple,
      FeesSettledEvent.OutputObject
    >;
    FeesSettled: TypedContractEvent<
      FeesSettledEvent.InputTuple,
      FeesSettledEvent.OutputTuple,
      FeesSettledEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Liquidated(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;
    Liquidated: TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;

    "PositionCloseRequested(address,bytes32,uint8)": TypedContractEvent<
      PositionCloseRequestedEvent.InputTuple,
      PositionCloseRequestedEvent.OutputTuple,
      PositionCloseRequestedEvent.OutputObject
    >;
    PositionCloseRequested: TypedContractEvent<
      PositionCloseRequestedEvent.InputTuple,
      PositionCloseRequestedEvent.OutputTuple,
      PositionCloseRequestedEvent.OutputObject
    >;

    "PositionOpenFailed(address,bytes32)": TypedContractEvent<
      PositionOpenFailedEvent.InputTuple,
      PositionOpenFailedEvent.OutputTuple,
      PositionOpenFailedEvent.OutputObject
    >;
    PositionOpenFailed: TypedContractEvent<
      PositionOpenFailedEvent.InputTuple,
      PositionOpenFailedEvent.OutputTuple,
      PositionOpenFailedEvent.OutputObject
    >;

    "PositionOpenRequested(address,bytes32,uint8,bool)": TypedContractEvent<
      PositionOpenRequestedEvent.InputTuple,
      PositionOpenRequestedEvent.OutputTuple,
      PositionOpenRequestedEvent.OutputObject
    >;
    PositionOpenRequested: TypedContractEvent<
      PositionOpenRequestedEvent.InputTuple,
      PositionOpenRequestedEvent.OutputTuple,
      PositionOpenRequestedEvent.OutputObject
    >;

    "PositionOpened(address,bytes32)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;

    "RBTCMinted(address,uint256)": TypedContractEvent<
      RBTCMintedEvent.InputTuple,
      RBTCMintedEvent.OutputTuple,
      RBTCMintedEvent.OutputObject
    >;
    RBTCMinted: TypedContractEvent<
      RBTCMintedEvent.InputTuple,
      RBTCMintedEvent.OutputTuple,
      RBTCMintedEvent.OutputObject
    >;

    "RBTCRepaid(address,uint256)": TypedContractEvent<
      RBTCRepaidEvent.InputTuple,
      RBTCRepaidEvent.OutputTuple,
      RBTCRepaidEvent.OutputObject
    >;
    RBTCRepaid: TypedContractEvent<
      RBTCRepaidEvent.InputTuple,
      RBTCRepaidEvent.OutputTuple,
      RBTCRepaidEvent.OutputObject
    >;

    "RedeemRequested(address,address,bytes32,uint256)": TypedContractEvent<
      RedeemRequestedEvent.InputTuple,
      RedeemRequestedEvent.OutputTuple,
      RedeemRequestedEvent.OutputObject
    >;
    RedeemRequested: TypedContractEvent<
      RedeemRequestedEvent.InputTuple,
      RedeemRequestedEvent.OutputTuple,
      RedeemRequestedEvent.OutputObject
    >;

    "Redeemed(address,address,uint256,uint256,uint256)": TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;
    Redeemed: TypedContractEvent<
      RedeemedEvent.InputTuple,
      RedeemedEvent.OutputTuple,
      RedeemedEvent.OutputObject
    >;

    "StopLossSet(address,bytes32,uint256)": TypedContractEvent<
      StopLossSetEvent.InputTuple,
      StopLossSetEvent.OutputTuple,
      StopLossSetEvent.OutputObject
    >;
    StopLossSet: TypedContractEvent<
      StopLossSetEvent.InputTuple,
      StopLossSetEvent.OutputTuple,
      StopLossSetEvent.OutputObject
    >;

    "StuckOrderRecovered(address,bytes32)": TypedContractEvent<
      StuckOrderRecoveredEvent.InputTuple,
      StuckOrderRecoveredEvent.OutputTuple,
      StuckOrderRecoveredEvent.OutputObject
    >;
    StuckOrderRecovered: TypedContractEvent<
      StuckOrderRecoveredEvent.InputTuple,
      StuckOrderRecoveredEvent.OutputTuple,
      StuckOrderRecoveredEvent.OutputObject
    >;

    "TakeProfitSet(address,bytes32,uint256)": TypedContractEvent<
      TakeProfitSetEvent.InputTuple,
      TakeProfitSetEvent.OutputTuple,
      TakeProfitSetEvent.OutputObject
    >;
    TakeProfitSet: TypedContractEvent<
      TakeProfitSetEvent.InputTuple,
      TakeProfitSetEvent.OutputTuple,
      TakeProfitSetEvent.OutputObject
    >;
  };
}
