/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type RiskParamsStruct = {
  maxLtv1xBps: BigNumberish;
  bufferBps: BigNumberish;
  maxLtvAtMaxLevBps: BigNumberish;
  flatTier: BigNumberish;
  maxLeverage: BigNumberish;
};

export type RiskParamsStructOutput = [
  maxLtv1xBps: bigint,
  bufferBps: bigint,
  maxLtvAtMaxLevBps: bigint,
  flatTier: bigint,
  maxLeverage: bigint
] & {
  maxLtv1xBps: bigint;
  bufferBps: bigint;
  maxLtvAtMaxLevBps: bigint;
  flatTier: bigint;
  maxLeverage: bigint;
};

export interface VaultFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMarket"
      | "avgHealthAcrossQueue"
      | "createVault"
      | "enqueueRedemption"
      | "gmxAdapter"
      | "implementation"
      | "inRedemptionQueue"
      | "isVault"
      | "marketCount"
      | "marketIds"
      | "markets"
      | "nextRedeemable"
      | "onCollateralChanged"
      | "owner"
      | "pause"
      | "paused"
      | "pruneRedemption"
      | "redeemableCount"
      | "redemptionQueueAt"
      | "redemptionQueueLength"
      | "renounceOwnership"
      | "setGmxAdapter"
      | "sweepFees"
      | "totalCollateralLocked"
      | "totalRedeemableDebt"
      | "totalVaults"
      | "transferOwnership"
      | "unpause"
      | "usdc"
      | "vaultOf"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketAdded"
      | "OwnershipTransferred"
      | "Paused"
      | "RedemptionDequeued"
      | "RedemptionEnqueued"
      | "SweptFees"
      | "Unpaused"
      | "VaultCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMarket",
    values: [BytesLike, AddressLike, string, string, RiskParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "avgHealthAcrossQueue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enqueueRedemption",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gmxAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inRedemptionQueue",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "nextRedeemable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onCollateralChanged",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pruneRedemption",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeemableCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionQueueAt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionQueueLength",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGmxAdapter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepFees",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateralLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRedeemableDebt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultOf",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addMarket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "avgHealthAcrossQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enqueueRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gmxAdapter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inRedemptionQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRedeemable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onCollateralChanged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pruneRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemableCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionQueueAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionQueueLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGmxAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweepFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateralLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRedeemableDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaultOf", data: BytesLike): Result;
}

export namespace MarketAddedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    oracle: AddressLike,
    rToken: AddressLike
  ];
  export type OutputTuple = [marketId: string, oracle: string, rToken: string];
  export interface OutputObject {
    marketId: string;
    oracle: string;
    rToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionDequeuedEvent {
  export type InputTuple = [marketId: BytesLike, vault: AddressLike];
  export type OutputTuple = [marketId: string, vault: string];
  export interface OutputObject {
    marketId: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionEnqueuedEvent {
  export type InputTuple = [marketId: BytesLike, vault: AddressLike];
  export type OutputTuple = [marketId: string, vault: string];
  export interface OutputObject {
    marketId: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SweptFeesEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    marketId: BytesLike,
    vault: AddressLike
  ];
  export type OutputTuple = [owner: string, marketId: string, vault: string];
  export interface OutputObject {
    owner: string;
    marketId: string;
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultFactory extends BaseContract {
  connect(runner?: ContractRunner | null): VaultFactory;
  waitForDeployment(): Promise<this>;

  interface: VaultFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMarket: TypedContractMethod<
    [
      marketId: BytesLike,
      oracle: AddressLike,
      name: string,
      symbol: string,
      risk: RiskParamsStruct
    ],
    [string],
    "nonpayable"
  >;

  avgHealthAcrossQueue: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  createVault: TypedContractMethod<
    [marketId: BytesLike],
    [string],
    "nonpayable"
  >;

  enqueueRedemption: TypedContractMethod<
    [marketId: BytesLike, vault: AddressLike],
    [void],
    "nonpayable"
  >;

  gmxAdapter: TypedContractMethod<[], [string], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  inRedemptionQueue: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isVault: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  marketIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, string, string, bigint, bigint, bigint, bigint, bigint] & {
        active: boolean;
        oracle: string;
        rToken: string;
        maxLtv1xBps: bigint;
        bufferBps: bigint;
        maxLtvAtMaxLevBps: bigint;
        flatTier: bigint;
        maxLeverage: bigint;
      }
    ],
    "view"
  >;

  nextRedeemable: TypedContractMethod<[marketId: BytesLike], [string], "view">;

  onCollateralChanged: TypedContractMethod<
    [delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pruneRedemption: TypedContractMethod<
    [marketId: BytesLike, index: BigNumberish],
    [void],
    "nonpayable"
  >;

  redeemableCount: TypedContractMethod<[marketId: BytesLike], [bigint], "view">;

  redemptionQueueAt: TypedContractMethod<
    [marketId: BytesLike, i: BigNumberish],
    [string],
    "view"
  >;

  redemptionQueueLength: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGmxAdapter: TypedContractMethod<[gmx_: AddressLike], [void], "nonpayable">;

  sweepFees: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalCollateralLocked: TypedContractMethod<[], [bigint], "view">;

  totalRedeemableDebt: TypedContractMethod<
    [marketId: BytesLike],
    [bigint],
    "view"
  >;

  totalVaults: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  vaultOf: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMarket"
  ): TypedContractMethod<
    [
      marketId: BytesLike,
      oracle: AddressLike,
      name: string,
      symbol: string,
      risk: RiskParamsStruct
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "avgHealthAcrossQueue"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<[marketId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "enqueueRedemption"
  ): TypedContractMethod<
    [marketId: BytesLike, vault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gmxAdapter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "inRedemptionQueue"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVault"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, string, string, bigint, bigint, bigint, bigint, bigint] & {
        active: boolean;
        oracle: string;
        rToken: string;
        maxLtv1xBps: bigint;
        bufferBps: bigint;
        maxLtvAtMaxLevBps: bigint;
        flatTier: bigint;
        maxLeverage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextRedeemable"
  ): TypedContractMethod<[marketId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "onCollateralChanged"
  ): TypedContractMethod<[delta: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pruneRedemption"
  ): TypedContractMethod<
    [marketId: BytesLike, index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "redeemableCount"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "redemptionQueueAt"
  ): TypedContractMethod<
    [marketId: BytesLike, i: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "redemptionQueueLength"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGmxAdapter"
  ): TypedContractMethod<[gmx_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sweepFees"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalCollateralLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRedeemableDebt"
  ): TypedContractMethod<[marketId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVaults"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultOf"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [string],
    "view"
  >;

  getEvent(
    key: "MarketAdded"
  ): TypedContractEvent<
    MarketAddedEvent.InputTuple,
    MarketAddedEvent.OutputTuple,
    MarketAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionDequeued"
  ): TypedContractEvent<
    RedemptionDequeuedEvent.InputTuple,
    RedemptionDequeuedEvent.OutputTuple,
    RedemptionDequeuedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionEnqueued"
  ): TypedContractEvent<
    RedemptionEnqueuedEvent.InputTuple,
    RedemptionEnqueuedEvent.OutputTuple,
    RedemptionEnqueuedEvent.OutputObject
  >;
  getEvent(
    key: "SweptFees"
  ): TypedContractEvent<
    SweptFeesEvent.InputTuple,
    SweptFeesEvent.OutputTuple,
    SweptFeesEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;

  filters: {
    "MarketAdded(bytes32,address,address)": TypedContractEvent<
      MarketAddedEvent.InputTuple,
      MarketAddedEvent.OutputTuple,
      MarketAddedEvent.OutputObject
    >;
    MarketAdded: TypedContractEvent<
      MarketAddedEvent.InputTuple,
      MarketAddedEvent.OutputTuple,
      MarketAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RedemptionDequeued(bytes32,address)": TypedContractEvent<
      RedemptionDequeuedEvent.InputTuple,
      RedemptionDequeuedEvent.OutputTuple,
      RedemptionDequeuedEvent.OutputObject
    >;
    RedemptionDequeued: TypedContractEvent<
      RedemptionDequeuedEvent.InputTuple,
      RedemptionDequeuedEvent.OutputTuple,
      RedemptionDequeuedEvent.OutputObject
    >;

    "RedemptionEnqueued(bytes32,address)": TypedContractEvent<
      RedemptionEnqueuedEvent.InputTuple,
      RedemptionEnqueuedEvent.OutputTuple,
      RedemptionEnqueuedEvent.OutputObject
    >;
    RedemptionEnqueued: TypedContractEvent<
      RedemptionEnqueuedEvent.InputTuple,
      RedemptionEnqueuedEvent.OutputTuple,
      RedemptionEnqueuedEvent.OutputObject
    >;

    "SweptFees(address,address,uint256)": TypedContractEvent<
      SweptFeesEvent.InputTuple,
      SweptFeesEvent.OutputTuple,
      SweptFeesEvent.OutputObject
    >;
    SweptFees: TypedContractEvent<
      SweptFeesEvent.InputTuple,
      SweptFeesEvent.OutputTuple,
      SweptFeesEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VaultCreated(address,bytes32,address)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
  };
}
