/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRYieldVaultHarvest,
  IRYieldVaultHarvestInterface,
} from "../../../src/RYieldStrategy.sol/IRYieldVaultHarvest";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "grossFundingUsdc",
        type: "uint256",
      },
    ],
    name: "harvestFunding",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRYieldVaultHarvest__factory {
  static readonly abi = _abi;
  static createInterface(): IRYieldVaultHarvestInterface {
    return new Interface(_abi) as IRYieldVaultHarvestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRYieldVaultHarvest {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRYieldVaultHarvest;
  }
}
