/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RYieldStrategyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DELTA_BAND_BPS"
      | "closeHedge"
      | "harvestShortFunding"
      | "keeper"
      | "longValueUsdc"
      | "marketId"
      | "openHedge"
      | "oracle"
      | "owner"
      | "rToken"
      | "rTokenBalance"
      | "reduceLong"
      | "renounceOwnership"
      | "returnToVault"
      | "setKeeper"
      | "shortKey"
      | "shortPerp"
      | "shortValueUsdc"
      | "swapPool"
      | "totalValueUsdc"
      | "transferOwnership"
      | "usdc"
      | "usdcBalance"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HedgeClosed"
      | "HedgeOpened"
      | "KeeperSet"
      | "LongReduced"
      | "OwnershipTransferred"
      | "ReturnedToVault"
      | "ShortFundingHarvested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DELTA_BAND_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeHedge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "harvestShortFunding",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "keeper", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "longValueUsdc",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "marketId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openHedge",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reduceLong",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnToVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "shortKey", values?: undefined): string;
  encodeFunctionData(functionFragment: "shortPerp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "shortValueUsdc",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "swapPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalValueUsdc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DELTA_BAND_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeHedge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestShortFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "keeper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "longValueUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "marketId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "openHedge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reduceLong", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setKeeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shortKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shortPerp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "shortValueUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalValueUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdcBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace HedgeClosedEvent {
  export type InputTuple = [shortPayout: BigNumberish, longUsdc: BigNumberish];
  export type OutputTuple = [shortPayout: bigint, longUsdc: bigint];
  export interface OutputObject {
    shortPayout: bigint;
    longUsdc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HedgeOpenedEvent {
  export type InputTuple = [
    usdcLong: BigNumberish,
    shortMargin: BigNumberish,
    shortSize: BigNumberish,
    shortKey: BytesLike
  ];
  export type OutputTuple = [
    usdcLong: bigint,
    shortMargin: bigint,
    shortSize: bigint,
    shortKey: string
  ];
  export interface OutputObject {
    usdcLong: bigint;
    shortMargin: bigint;
    shortSize: bigint;
    shortKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeeperSetEvent {
  export type InputTuple = [keeper: AddressLike];
  export type OutputTuple = [keeper: string];
  export interface OutputObject {
    keeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LongReducedEvent {
  export type InputTuple = [rTokenIn: BigNumberish, usdcOut: BigNumberish];
  export type OutputTuple = [rTokenIn: bigint, usdcOut: bigint];
  export interface OutputObject {
    rTokenIn: bigint;
    usdcOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReturnedToVaultEvent {
  export type InputTuple = [usdcOut: BigNumberish];
  export type OutputTuple = [usdcOut: bigint];
  export interface OutputObject {
    usdcOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShortFundingHarvestedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RYieldStrategy extends BaseContract {
  connect(runner?: ContractRunner | null): RYieldStrategy;
  waitForDeployment(): Promise<this>;

  interface: RYieldStrategyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DELTA_BAND_BPS: TypedContractMethod<[], [bigint], "view">;

  closeHedge: TypedContractMethod<
    [minUsdcOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  harvestShortFunding: TypedContractMethod<[], [bigint], "nonpayable">;

  keeper: TypedContractMethod<[], [string], "view">;

  longValueUsdc: TypedContractMethod<[], [bigint], "view">;

  marketId: TypedContractMethod<[], [string], "view">;

  openHedge: TypedContractMethod<
    [
      usdcLong: BigNumberish,
      shortMargin: BigNumberish,
      shortSize: BigNumberish,
      minRBtcOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rToken: TypedContractMethod<[], [string], "view">;

  rTokenBalance: TypedContractMethod<[], [bigint], "view">;

  reduceLong: TypedContractMethod<
    [rTokenIn: BigNumberish, minUsdcOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  returnToVault: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setKeeper: TypedContractMethod<[keeper_: AddressLike], [void], "nonpayable">;

  shortKey: TypedContractMethod<[], [string], "view">;

  shortPerp: TypedContractMethod<[], [string], "view">;

  shortValueUsdc: TypedContractMethod<[], [bigint], "view">;

  swapPool: TypedContractMethod<[], [string], "view">;

  totalValueUsdc: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  usdcBalance: TypedContractMethod<[], [bigint], "view">;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DELTA_BAND_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "closeHedge"
  ): TypedContractMethod<[minUsdcOut: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "harvestShortFunding"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "keeper"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "longValueUsdc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "openHedge"
  ): TypedContractMethod<
    [
      usdcLong: BigNumberish,
      shortMargin: BigNumberish,
      shortSize: BigNumberish,
      minRBtcOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rTokenBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reduceLong"
  ): TypedContractMethod<
    [rTokenIn: BigNumberish, minUsdcOut: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnToVault"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKeeper"
  ): TypedContractMethod<[keeper_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shortKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "shortPerp"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "shortValueUsdc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalValueUsdc"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdcBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "HedgeClosed"
  ): TypedContractEvent<
    HedgeClosedEvent.InputTuple,
    HedgeClosedEvent.OutputTuple,
    HedgeClosedEvent.OutputObject
  >;
  getEvent(
    key: "HedgeOpened"
  ): TypedContractEvent<
    HedgeOpenedEvent.InputTuple,
    HedgeOpenedEvent.OutputTuple,
    HedgeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "KeeperSet"
  ): TypedContractEvent<
    KeeperSetEvent.InputTuple,
    KeeperSetEvent.OutputTuple,
    KeeperSetEvent.OutputObject
  >;
  getEvent(
    key: "LongReduced"
  ): TypedContractEvent<
    LongReducedEvent.InputTuple,
    LongReducedEvent.OutputTuple,
    LongReducedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReturnedToVault"
  ): TypedContractEvent<
    ReturnedToVaultEvent.InputTuple,
    ReturnedToVaultEvent.OutputTuple,
    ReturnedToVaultEvent.OutputObject
  >;
  getEvent(
    key: "ShortFundingHarvested"
  ): TypedContractEvent<
    ShortFundingHarvestedEvent.InputTuple,
    ShortFundingHarvestedEvent.OutputTuple,
    ShortFundingHarvestedEvent.OutputObject
  >;

  filters: {
    "HedgeClosed(uint256,uint256)": TypedContractEvent<
      HedgeClosedEvent.InputTuple,
      HedgeClosedEvent.OutputTuple,
      HedgeClosedEvent.OutputObject
    >;
    HedgeClosed: TypedContractEvent<
      HedgeClosedEvent.InputTuple,
      HedgeClosedEvent.OutputTuple,
      HedgeClosedEvent.OutputObject
    >;

    "HedgeOpened(uint256,uint256,uint256,bytes32)": TypedContractEvent<
      HedgeOpenedEvent.InputTuple,
      HedgeOpenedEvent.OutputTuple,
      HedgeOpenedEvent.OutputObject
    >;
    HedgeOpened: TypedContractEvent<
      HedgeOpenedEvent.InputTuple,
      HedgeOpenedEvent.OutputTuple,
      HedgeOpenedEvent.OutputObject
    >;

    "KeeperSet(address)": TypedContractEvent<
      KeeperSetEvent.InputTuple,
      KeeperSetEvent.OutputTuple,
      KeeperSetEvent.OutputObject
    >;
    KeeperSet: TypedContractEvent<
      KeeperSetEvent.InputTuple,
      KeeperSetEvent.OutputTuple,
      KeeperSetEvent.OutputObject
    >;

    "LongReduced(uint256,uint256)": TypedContractEvent<
      LongReducedEvent.InputTuple,
      LongReducedEvent.OutputTuple,
      LongReducedEvent.OutputObject
    >;
    LongReduced: TypedContractEvent<
      LongReducedEvent.InputTuple,
      LongReducedEvent.OutputTuple,
      LongReducedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReturnedToVault(uint256)": TypedContractEvent<
      ReturnedToVaultEvent.InputTuple,
      ReturnedToVaultEvent.OutputTuple,
      ReturnedToVaultEvent.OutputObject
    >;
    ReturnedToVault: TypedContractEvent<
      ReturnedToVaultEvent.InputTuple,
      ReturnedToVaultEvent.OutputTuple,
      ReturnedToVaultEvent.OutputObject
    >;

    "ShortFundingHarvested(uint256)": TypedContractEvent<
      ShortFundingHarvestedEvent.InputTuple,
      ShortFundingHarvestedEvent.OutputTuple,
      ShortFundingHarvestedEvent.OutputObject
    >;
    ShortFundingHarvested: TypedContractEvent<
      ShortFundingHarvestedEvent.InputTuple,
      ShortFundingHarvestedEvent.OutputTuple,
      ShortFundingHarvestedEvent.OutputObject
    >;
  };
}
