/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IGmxReader {
  export type PositionAddressesStruct = {
    account: AddressLike;
    market: AddressLike;
    collateralToken: AddressLike;
  };

  export type PositionAddressesStructOutput = [
    account: string,
    market: string,
    collateralToken: string
  ] & { account: string; market: string; collateralToken: string };

  export type PositionNumbersStruct = {
    sizeInUsd: BigNumberish;
    sizeInTokens: BigNumberish;
    collateralAmount: BigNumberish;
    borrowingFactor: BigNumberish;
    fundingFeeAmountPerSize: BigNumberish;
    longTokenClaimableFundingAmountPerSize: BigNumberish;
    shortTokenClaimableFundingAmountPerSize: BigNumberish;
    increasedAtTime: BigNumberish;
    decreasedAtTime: BigNumberish;
  };

  export type PositionNumbersStructOutput = [
    sizeInUsd: bigint,
    sizeInTokens: bigint,
    collateralAmount: bigint,
    borrowingFactor: bigint,
    fundingFeeAmountPerSize: bigint,
    longTokenClaimableFundingAmountPerSize: bigint,
    shortTokenClaimableFundingAmountPerSize: bigint,
    increasedAtTime: bigint,
    decreasedAtTime: bigint
  ] & {
    sizeInUsd: bigint;
    sizeInTokens: bigint;
    collateralAmount: bigint;
    borrowingFactor: bigint;
    fundingFeeAmountPerSize: bigint;
    longTokenClaimableFundingAmountPerSize: bigint;
    shortTokenClaimableFundingAmountPerSize: bigint;
    increasedAtTime: bigint;
    decreasedAtTime: bigint;
  };

  export type PositionFlagsStruct = { isLong: boolean };

  export type PositionFlagsStructOutput = [isLong: boolean] & {
    isLong: boolean;
  };

  export type PositionPropsStruct = {
    addresses: IGmxReader.PositionAddressesStruct;
    numbers: IGmxReader.PositionNumbersStruct;
    flags: IGmxReader.PositionFlagsStruct;
  };

  export type PositionPropsStructOutput = [
    addresses: IGmxReader.PositionAddressesStructOutput,
    numbers: IGmxReader.PositionNumbersStructOutput,
    flags: IGmxReader.PositionFlagsStructOutput
  ] & {
    addresses: IGmxReader.PositionAddressesStructOutput;
    numbers: IGmxReader.PositionNumbersStructOutput;
    flags: IGmxReader.PositionFlagsStructOutput;
  };
}

export interface IGmxReaderInterface extends Interface {
  getFunction(nameOrSignature: "getPosition"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPosition",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
}

export interface IGmxReader extends BaseContract {
  connect(runner?: ContractRunner | null): IGmxReader;
  waitForDeployment(): Promise<this>;

  interface: IGmxReaderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPosition: TypedContractMethod<
    [dataStore: AddressLike, key: BytesLike],
    [IGmxReader.PositionPropsStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [dataStore: AddressLike, key: BytesLike],
    [IGmxReader.PositionPropsStructOutput],
    "view"
  >;

  filters: {};
}
