/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IShortPerpInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accruedFunding"
      | "claimFunding"
      | "closeShort"
      | "openShort"
      | "positionValueUsdc"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accruedFunding",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFunding",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeShort",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openShort",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "positionValueUsdc",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accruedFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimFunding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeShort", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "openShort", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionValueUsdc",
    data: BytesLike
  ): Result;
}

export interface IShortPerp extends BaseContract {
  connect(runner?: ContractRunner | null): IShortPerp;
  waitForDeployment(): Promise<this>;

  interface: IShortPerpInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accruedFunding: TypedContractMethod<[key: BytesLike], [bigint], "view">;

  claimFunding: TypedContractMethod<[key: BytesLike], [bigint], "nonpayable">;

  closeShort: TypedContractMethod<[key: BytesLike], [bigint], "nonpayable">;

  openShort: TypedContractMethod<
    [marginUsdc: BigNumberish, sizeUsdc: BigNumberish],
    [string],
    "nonpayable"
  >;

  positionValueUsdc: TypedContractMethod<[key: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accruedFunding"
  ): TypedContractMethod<[key: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimFunding"
  ): TypedContractMethod<[key: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "closeShort"
  ): TypedContractMethod<[key: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "openShort"
  ): TypedContractMethod<
    [marginUsdc: BigNumberish, sizeUsdc: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "positionValueUsdc"
  ): TypedContractMethod<[key: BytesLike], [bigint], "view">;

  filters: {};
}
